### ISSUE TITLE
New version tags for updates containing breaking changes

### ISSUE THREAD

**Issue by Nixname5** [minidocks/inkscape#1]
Hello,

I am using your Docker images to convert svg images to pdf files for use when compiling LaTeX.
I downloaded the tag 0.92 on a new computer and tried to compile the images, which failed with the following output:
** (inkscape:143): WARNING **: 09:35:38.324: Invalid option --export-type=pdf

You can imagine my surprise, since with just the same setup the compilation worked on my different PC. The reason was the update of the tag 0.92, which apparently introduces a breaking change.
To avoid breaking updates I had already specified the version as explicitly as possible by using the tag 0.92.
Don't get me wrong, I do appreciate updates, but please use a different tag when pushing updates, at least when they contain breaking changes, so the users can choose when to update.

**Comment by hason** [comment]
I apologize for the inconvenience. Accidentally updated inkscape to version 1.0 in tag 0.92.
